services:
  mariadb:
    image: inception-mariadb
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    hostname: ${MARIADB_HOST}
    environment:
      - MARIADB_WP_DB
      - MARIADB_WP_ADMIN
      - MARIADB_WP_USER
    secrets:
      - mariadb_root_password
      - mariadb_wp_admin_password
      - mariadb_wp_user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
  wordpress:
    image: inception-wordpress
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    hostname: ${WORDPRESS_HOST}
    environment:
      - SITE_FQDN
      - MARIADB_HOST
      - MARIADB_WP_DB
      - MARIADB_WP_USER
      - WP_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_EMAIL
    secrets:
      - mariadb_wp_user_password
      - wp_admin_password
    volumes:
      - wordpress_data:/var/www
    networks:
      - backend
    depends_on:
      - mariadb
  nginx:
    image: inception-nginx
    build:
      context: ./requirements/nginx/
    container_name: nginx
    hostname: ${SITE_FQDN}
    environment:
      - SITE_FQDN
      - WORDPRESS_HOST
    secrets:
      - ssl_cert
      - ssl_key
    volumes:
      - wordpress_data:/var/www
    networks:
      - backend
    depends_on:
      - wordpress
    ports:
      - 443:443

secrets:
  mariadb_root_password:
    file: ../secrets/db_root_password.txt
  mariadb_wp_admin_password:
    file: ../secrets/db_admin_password.txt
  mariadb_wp_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  ssl_cert:
    file: ../secrets/amoutill.42.fr.crt
  ssl_key:
    file: ../secrets/amoutill.42.fr.key

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data

networks:
  backend:
    name: backend
