services:
  mariadb:
    image: inception-mariadb
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    secrets:
      - mariadb_root_password
      - mariadb_wp_admin_password
      - mariadb_wp_user_password
    env_file: .db_env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
  wordpress:
    image: inception-wordpress
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www
    networks:
      - backend
  nginx:
    image: inception-nginx
    build:
      context: ./requirements/nginx/
    container_name: nginx
    volumes:
      - wordpress_data:/var/www
    networks:
      - backend
    ports:
      - 443:443

secrets:
  mariadb_root_password:
    file: ../secrets/db_root_password.txt
  mariadb_wp_admin_password:
    file: ../secrets/db_admin_password.txt
  mariadb_wp_user_password:
    file: ../secrets/db_user_password.txt

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data

networks:
  backend:
    name: backend
